# Generated by Django 5.1.7 on 2025-05-05 00:49

import datetime
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('fakultas', models.CharField(max_length=50)),
                ('angkatan', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
                ('dibaca', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balasan', to='admin_ukm.pesan')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan_diterima', to=settings.AUTH_USER_MODEL)),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan_dikirim', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ukm_logos/')),
                ('deskripsi_singkat', tinymce.models.HTMLField()),
                ('visi', tinymce.models.HTMLField()),
                ('misi', tinymce.models.HTMLField()),
                ('jenis_kegiatan', models.CharField(choices=[('seni', 'Seni'), ('olahraga', 'Olahraga'), ('akademik', 'Akademik'), ('sosial', 'Sosial'), ('teknologi', 'Teknologi'), ('lainnya', 'Lainnya')], max_length=50)),
                ('hari_mulai', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu'), ('minggu', 'Minggu')], max_length=20)),
                ('hari_selesai', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu'), ('minggu', 'Minggu')], max_length=20)),
                ('waktu_mulai', models.TimeField(default=datetime.time(8, 0))),
                ('waktu_selesai', models.TimeField(default=datetime.time(17, 0))),
                ('ketua_ukm', models.CharField(max_length=100)),
                ('pengurus_pendaftaran', models.CharField(max_length=100)),
                ('persyaratan_umum', tinymce.models.HTMLField()),
                ('berkas_dibutuhkan_json', models.TextField(default='[]')),
                ('alur_pendaftaran_json', models.TextField(default='[]')),
                ('periode_pendaftaran_mulai', models.DateField(blank=True, null=True)),
                ('periode_pendaftaran_selesai', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_ukm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendaftaranUKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='pendaftar/foto_profil/')),
                ('dokumen_ktm', models.FileField(blank=True, null=True, upload_to='pendaftar/dokumen_ktm/')),
                ('dokumen_cv', models.FileField(blank=True, null=True, upload_to='pendaftar/dokumen_cv/')),
                ('dokumen_surat_minat', models.FileField(blank=True, null=True, upload_to='pendaftar/dokumen_surat_minat/')),
                ('dokumen_lainnya', models.FileField(blank=True, null=True, upload_to='pendaftar/dokumen_lainnya/')),
                ('status', models.CharField(choices=[('diproses', 'Diproses'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='diproses', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran_ukm', to='admin_ukm.mahasiswa')),
                ('ukm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ukm.ukm')),
            ],
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_aktif', models.BooleanField(default=True)),
                ('tanggal_bergabung', models.DateField(auto_now_add=True)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ukm.pendaftaranukm')),
                ('ukm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ukm.ukm')),
            ],
        ),
    ]
